drop table if exists bookmarks;

CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  rating INTEGER
);

INSERT INTO bookmarks (name, url, description, rating)
values
  ('Google', 'https://www.google.com', 'Your search engine', 5),
  ('Thinkful', 'https://www.thinkful.com', 'The best', 5),
  ('Yahoo', 'https://www.yahoo.com', 'If it were not for fantasy sports...', 1),
  ('Pitcher List', 'https://www.pitcherlist.com', 'Good stuff!', 5),
  ('Reddit', 'https://www.reddit.com', 'Time suck', 2),
  ('Nothing', 'https://www.nothing.com', null, null),
  ('Number 7', 'https://www.number7.com', 'I do not know', null),
  ('Amazon', 'https://www.amazon.com', 'Our future overlords', 3),
  ('Getting to the end', 'https://www.almost-there.com', null, null),
  ('Fin', 'https://www.flipper.com', 'I meant the French word', null);